# Lesson 28.NumPy数组的常用方法

&emsp;&emsp;本节继续介绍NumPy中一些特殊数组的创建方法，以及数组使用的常用方法。

In [1]:
import numpy as np

### 1.特殊数组的创建方法

&emsp;&emsp;既然数组可以类比于向量和矩阵，那么一些特殊的向量和矩阵的创建方法，数组也同样支持。

- 全0数组

In [3]:
np.zeros(6)                      # 默认是浮点型

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros(6, dtype='int')         # 转化为整型

array([0, 0, 0, 0, 0, 0])

- 全1数组

In [9]:
np.ones((3, 2))                  # 三行两列

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

- 随机数组：rand生成服从01分布的随机数

In [12]:
np.random.rand(5)                # 返回服从01分布的5个数

array([0.87297283, 0.93368085, 0.36421553, 0.18778593, 0.93113471])

In [17]:
np.mean(np.random.rand(5))

0.3583378815778427

In [18]:
np.mean(np.random.rand(5000))

0.4915722653606632

In [19]:
np.mean(np.random.rand(50000000))

0.49999435963899275

In [22]:
np.random.rand(2, 5)              # 可以直接生成两行五列的随机数组

array([[0.84978987, 0.59547711, 0.94730639, 0.44975163, 0.16235556],
       [0.70415126, 0.85891545, 0.99494518, 0.09302874, 0.87909135]])

- 随机数组：randn生成标准正态分布的随机数

In [23]:
np.random.randn(5) 

array([ 1.84519234,  0.44723496,  0.61016206, -0.39027894, -0.26761442])

In [24]:
np.mean(np.random.randn(100000))         # 均值

-0.0013472347810240376

In [25]:
np.mean(np.random.randn(100000000))

0.00021197962428539123

In [27]:
np.var(np.random.randn(100000))         # 方差

0.9956951293762225

- 随机数组：normal生成元素是指定随机分布的数组

In [29]:
np.random.normal(4, 2, (3,3))          # 三行三列，元素服从均值4、方差为2的正态分布

array([[ 5.53705005,  1.95477989,  3.07768639],
       [ 4.15457427,  3.69587242,  3.18715934],
       [ 5.46093734,  6.60888084, -0.55980278]])

- 生成全数值相同的数组

In [30]:
np.full((2, 2), 3)

array([[3, 3],
       [3, 3]])

- 生成单位矩阵

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- 生成对角矩阵

In [33]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

- 按照某种形状生成ndarray

In [35]:
e = [[2,1,3],[4,3,2]]

In [36]:
np.array(e)

array([[2, 1, 3],
       [4, 3, 2]])

In [37]:
np.ones_like(e)
np.zeros_like(e)
np.full_like(e,5)

array([[5, 5, 5],
       [5, 5, 5]])

### 2.数组常用变形方法

&emsp;&emsp;类似于矩阵，数组在执行实际运算过程中，也经常会涉及一些形变的方法。

- reshape方法：调整数组行列结构

In [39]:
a1 = np.random.rand(2, 3)
a1

array([[0.56262855, 0.73129141, 0.86289312],
       [0.93186546, 0.93884182, 0.22485166]])

In [40]:
a1.shape

(2, 3)

In [41]:
a1.reshape(3, 2)

array([[0.56262855, 0.73129141],
       [0.86289312, 0.93186546],
       [0.93884182, 0.22485166]])

In [42]:
a1.reshape(1, -1)          # 可以将-1理解为占位符

array([[0.56262855, 0.73129141, 0.86289312, 0.93186546, 0.93884182,
        0.22485166]])

In [43]:
a1.reshape(-1, 1)

array([[0.56262855],
       [0.73129141],
       [0.86289312],
       [0.93186546],
       [0.93884182],
       [0.22485166]])

但此时，需要注意的是，转化后的数组仍然是二维数组。若要实现维度的转化，则需要使用flatten函数。

- flatten方法：将数组降为一维数组

a1.flatten()

In [45]:
a1.flatten().shape

(6,)

- .T方法：数组的转置

In [47]:
a1

array([[0.56262855, 0.73129141, 0.86289312],
       [0.93186546, 0.93884182, 0.22485166]])

In [49]:
a1.T                    # 就类似于矩阵的转置

array([[0.56262855, 0.93186546],
       [0.73129141, 0.93884182],
       [0.86289312, 0.22485166]])

In [50]:
np.random.rand(5)

array([0.85063203, 0.61416726, 0.17475127, 0.94200944, 0.93646733])

### 3.数组的拼接

&emsp;&emsp;对属于数组而言，由于经常涉及到数组的组合运算，因此数组和数组之间的组合拼接，对于数据技术来说，也是常用操作。

In [54]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])

In [56]:
a1, a2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

- vstack：纵向拼接，按列拼接，新增行，上下拼接

In [62]:
np.vstack([a1, a2])             # 需要输入一个序列

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
np.vstack((a1, a2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

- hstack：横向拼接，按行拼接，新增列，左右拼接

In [66]:
np.hstack([a1, a2]) 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### 4.数组的切分

&emsp;&emsp;当然，有拼接就有切分。接下来，简单看下数组的切分方法。拼接时关键字是`stack`，切分时关键字是`split`。

In [68]:
a = np.arange(24).reshape(3,8)          # 创建3行8列的二维数组
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

- hsplit：左右切分

In [77]:
# 当第二个参数只输入一个数时，是进行等分
np.hsplit(a,2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23]])]

In [79]:
# 无法等分的情况
np.hsplit(a,3)

ValueError: array split does not result in an equal division

In [81]:
# 当第二个参数输入一个序列时，则是根据列标进行切分
np.hsplit(a,(1,2,3))          # 第一列、第二列、第三列后进行切分

[array([[ 0],
        [ 8],
        [16]]),
 array([[ 1],
        [ 9],
        [17]]),
 array([[ 2],
        [10],
        [18]]),
 array([[ 3,  4,  5,  6,  7],
        [11, 12, 13, 14, 15],
        [19, 20, 21, 22, 23]])]

In [53]:
a1,a2 = np.hsplit(a,2)
a1
a2

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

- vsplit：上下切分

In [82]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [83]:
np.vsplit(a,3)                # 三等分

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]])]

In [89]:
np.vsplit(a,(1, ))            # 第一行后进行切分

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])]

思考，此处第二个参数位能否使用(1)?

- array_split：通用切分方法

In [90]:
# 均分
np.array_split(a, 2, axis=1)        # axis = 1，左右切分

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23]])]

In [93]:
# 根据列标进行切分
np.array_split(a, (1, ), axis=1)

[array([[ 0],
        [ 8],
        [16]]),
 array([[ 1,  2,  3,  4,  5,  6,  7],
        [ 9, 10, 11, 12, 13, 14, 15],
        [17, 18, 19, 20, 21, 22, 23]])]

In [91]:
# 均分
np.array_split(a, 3, axis=0)         # axis = 0，上下切分

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]])]

In [94]:
# 根据行标进行切分
np.array_split(a, (1, ), axis=0)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])]