# Lesson 28.Numpy的广播与科学计算

In [1]:
import numpy as np

&emsp;&emsp;Numpy所具备的广播特性，可以使得数组的科学计算变得高效而便捷，是NumPy最核大的特色之一。在Lesson 25中，我们尝试着用Array创建了三维坐标空间里的两个点，简单的矢量计算就得出了各维度的差值，其实就是利用了数组的广播特性。

In [2]:
x = np.array([1, 2, 3])                   
y = np.array([2, 2, 1])
x, y

(array([1, 2, 3]), array([2, 2, 1]))

In [3]:
x - y

array([-1,  0,  2])

这里我们看到，两个三个元素的数组，在进行减法运算时，每个位置上的元素依次相减。而更为一般的情况是两个不同形状的数组进行运算，此时数组也可利用广播完成计算。当然，目前也有很多材料认为，只有不同形状的数组在进行计算时，才用到了广播特性。

### 1.NumPy广播计算规则

首先，我们给出广播示意图：

![_auto_0](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

In [4]:
np.arange(3)

array([0, 1, 2])

In [5]:
np.arange(3) + 5  

array([5, 6, 7])

相当于每个位置元素依次加5，我们理解为，在计算的过程中5自动拓展成了一个1 * 3的数组，从而执行了和前者各位置上一一对应的相加。

In [8]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
b = np.arange(3)
b

array([0, 1, 2])

In [10]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

相当于a的每一行都分别和[1, 2, 3]进行相加，我们也可以理解成是b自动纵向拓展为了一个3 * 3的数组，从而完成对应位置上依次相加。当然，由于b本身就是行向量，因此只会纵向拓展。

In [15]:
a = np.arange(3).reshape((3, 1))
a

array([[0],
       [1],
       [2]])

In [17]:
b = np.arange(3)
b

array([0, 1, 2])

In [18]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

相当于a进行了横向拓展、b进行了纵向拓展，之后进行对应位置元素求和。

值得注意的是，如果两个数组的形状在任何一个维度上都不匹配并且没有任何一个维度为1，则会引发异常无法广播

In [20]:
a = np.ones((3,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
b = np.arange(3)
b

array([0, 1, 2])

In [22]:
a + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

得益于数组的广播特性，数组计算的条件得以极大的拓宽，接下来，就让我们看下数组的常用计算。

### 2.数组的算数运算

&emsp;&emsp;首先，来看数组算数运算。数组的算数运算和Python的数值型对象的算数运算非常类似，只不过当我们输入对象是个数组时，相关运算会作用于每个元素身上。相关运算函数及说明如下：

|**数学运算函数**|**描述**|
| -------------------------- | ---------------------------------------- |
| np.add(x1，x2 )      | 按元素添加参数，等效于 x1 + x2           |
| np.subtract(x1，x2) | 按元素方式减去参数，等效于x1 - x2        |
| np.multiply(x1，x2) | 逐元素乘法参数，等效于x1 * x2            |
| np.divide(x1，x2)   | 逐元素除以参数，等效于x1 / x2            |
| np.exp(x)           | 计算e的x次方。     |
| np.exp2(x)          | 计算2的x次方。 |
| np.power(x1,x2)     | 计算x1的x2次幂。                      |
| np.mod(x)             | 返回输入数组中相应元素的除法余数.       |
| np.log(x)           | 自然对数，逐元素。                       |
| np.log2(x)          | *x*的基础2对数。                         |
| np.log10(x)         | 以元素为单位返回输入数组的基数10的对数。 |
| np.expm1(x)         | 对数组中的所有元素计算`exp（x） - 1`     |
| np.log1p(x)         | 返回一个加自然对数的输入数组。     |
| np.sqrt(x)          | 按元素方式返回数组的正平方根。           |
| np.square(x)        | 返回输入的元素平方。                     |
| np.sin(x)           | 三角正弦。                               |
| np.cos(x)           | 元素余弦。                               |
| np.tan(x)           | 逐元素计算切线。                         |
| np.round(x)           | 四舍五入                               |
| np.floor(x)           | 向下取整                               |
| np.ceil(x)           | 向上取整                         |

In [26]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
b = np.array([10,11,12])
b

array([10, 11, 12])

In [29]:
np.add(a, b)             

array([[10, 12, 14],
       [13, 15, 17],
       [16, 18, 20]])

In [30]:
a + b

array([[10, 12, 14],
       [13, 15, 17],
       [16, 18, 20]])

In [31]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [32]:
np.cos(b)

array([-0.83907153,  0.0044257 ,  0.84385396])

In [37]:
c = np.random.randn(3)
c

array([-0.14336793,  0.00578218, -0.60752089])

In [38]:
np.round(c)

array([-0.,  0., -1.])

In [41]:
np.round(c)[1] == np.round(c)[0]

True

In [42]:
np.round(c, 1)          # 设置四舍五入精度

array([-0.1,  0. , -0.6])

In [43]:
np.floor(c)

array([-1.,  0., -1.])

关于其他科学计算函数，同学可以自行进行尝试。

### 3.数组的统计函数

&emsp;&emsp;NumPy有很多有用的统计函数，用于从数组中给定的元素中查找最小，最大，百分标准差和方差等。    
**常用统计函数：**

     
| **函数名称** |**NaN安全版本**|**描述**|   
| ---------|----|------------------ |   
|np.sum() |np.nansum()|计算元素的和|   
|np.min() |np.nanmin() |找出最小值|   
|np.max() |np.nanmax()|找出最大值|   
|np.prod() |np.nanprod()|计算元素的积|   
|np.ptp()  |N/A|计算元素的极差（最大值 - 最小值）|   
|np.mean()|np.nanmean()|计算元素的算术平均值|   
|np.std()|np.nanstd()|计算标准差|   
|np.var()|np.nanvar()|计算方差|   
|np.percentile()|np.nanpercentile()|计算百分位数|   
|np.median()|np.nanmedian()|计算中位数|   
|np.average()|N/A|返回数组的加权平均值|  
|np.any()|N/A |验证任何一个元素是否为真|   
|np.all()|N/A|验证所有元素是否为真|  

关于NaN安全版本的说明：数组出现NaN空值将影响最终结果输出，如果不希望空值带入计算，则可使用NaN安全版本

In [44]:
a = np.array([4,3,5,np.nan,6,3,5,2,7])

In [45]:
np.sum(a)

nan

In [46]:
np.nansum(a)

35.0

In [47]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [48]:
np.min(a)                  # 所有元素中最小的元素

2

In [51]:
np.min(a, axis = 0)        # 每一列中最小的元素     

array([2, 4, 3])

In [53]:
np.max(a, axis = 1)        # 每一行中最大的元素     

array([7, 8, 9])

In [54]:
np.ptp(a)                  # 所有元素的极差

7

In [56]:
np.ptp(a, axis = 0)        # 每一列的极差

array([6, 3, 6])

In [58]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [69]:
np.percentile(a, 70, axis = 0)          # 计算百分位数

array([2.4, 3.4])

In [70]:
1 + (3-1) * 0.7

2.4

In [71]:
np.percentile(a, 50, axis = 1)

array([1.5, 3.5])

**np.average()**    
&emsp;加权平均值是由每个分量乘以反映其重要性的因子得到的平均值。函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。该函数可以接受一个轴参数。如果没有指定轴，则数组会被展开。     
&emsp;考虑数组 [1,2,3,4] 和相应的权重 [4,3,2,1] ，通过将相应元素的乘积相加，并将和除以权重的和，来计算加权平均值。    
加权平均值 = `(1*4+2*3+3*2+4*1)/(4+3+2+1)`

In [72]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [73]:
#不指定权重时相当于 mean 函数
np.average(a)

2.5

In [74]:
wts = np.array([4,3,2,1])
np.average(a,weights = wts)

2.0

In [76]:
#如果 returned 参数设为 true，则额外返回权重的和
np.average([1,2,3,4],weights=[4,3,2,1], returned=True)

(2.0, 10.0)

### 4.数组的线性代数函数

NumPy拥有numpy.linalg 模块，提供线性代数所需的所有功能。
- np.dot() 返回两个数组的点积
- np.vdot() 返回两个向量的点积
- np.inner() 返回一维数组的向量内积
- np.matmul() 返回两个数组的矩阵乘积
- np.linalg.det() 计算输入矩阵的行列式
- np.linalg.solve() 求解矩阵形式的线性方程的解
- np.linalg.inv() 计算矩阵的逆

In [77]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [78]:
b = np.array([[11,12],[13,14]])
b

array([[11, 12],
       [13, 14]])

In [80]:
np.dot(a,b)                    # 相当于矩阵乘法

array([[37, 40],
       [85, 92]])

在较新版本中支持了以 @ 符号来表示矩阵的乘法

In [14]:
a @ b

array([[37, 40],
       [85, 92]])

numpy.vdot()  
此函数返回两个向量的点积。如果第一个参数是复数，那么它的共轭复数会用于计算。如果参数是多维数组，它会被展开。

In [81]:
np.vdot(a,b)

130

In [85]:
np.dot(a.flatten(), b.flatten().reshape(-1, 1))

array([130])

In [86]:
a

array([[1, 2],
       [3, 4]])

In [87]:
b

array([[11, 12],
       [13, 14]])

In [22]:
np.inner(a, b)

array([[35, 41],
       [81, 95]])

上面的例子中，内积计算如下： 

$ 1*11+2*12 $, $ 1*13+2*14 $  
$ 3*11+4*12 $, $ 3*13+4*14 $   

numpy.linalg.inv()   
函数来计算矩阵的逆。

In [88]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [89]:
y = np.linalg.inv(x)
y

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [90]:
np.dot(x,y)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])